require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_modules", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # UserModule. As you add validations to UserModule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UserModule.create! valid_attributes
      get user_modules_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user_module = UserModule.create! valid_attributes
      get user_module_url(user_module)
      expect(response).to be_successful
    end
  end

  # describe "GET /new" do
  #   it "renders a successful response" do
  #     get new_user_module_url
  #     expect(response).to be_successful
  #   end
  # end

  describe "GET /edit" do
    it "renders a successful response" do
      user_module = UserModule.create! valid_attributes
      get edit_user_module_url(user_module)
      expect(response).to be_successful
    end
  end

  # describe "POST /create" do
  #   context "with valid parameters" do
  #     it "creates a new UserModule" do
  #       expect {
  #         post user_modules_url, params: { user_module: valid_attributes }
  #       }.to change(UserModule, :count).by(1)
  #     end

  #     it "redirects to the created user_module" do
  #       post user_modules_url, params: { user_module: valid_attributes }
  #       expect(response).to redirect_to(user_module_url(UserModule.last))
  #     end
  #   end

  #   context "with invalid parameters" do
  #     it "does not create a new UserModule" do
  #       expect {
  #         post user_modules_url, params: { user_module: invalid_attributes }
  #       }.to change(UserModule, :count).by(0)
  #     end

  #     it "renders a successful response (i.e. to display the 'new' template)" do
  #       post user_modules_url, params: { user_module: invalid_attributes }
  #       expect(response).to be_successful
  #     end
  #   end
  # end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user_module" do
        user_module = UserModule.create! valid_attributes
        patch user_module_url(user_module), params: { user_module: new_attributes }
        user_module.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the user_module" do
        user_module = UserModule.create! valid_attributes
        patch user_module_url(user_module), params: { user_module: new_attributes }
        user_module.reload
        expect(response).to redirect_to(user_module_url(user_module))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        user_module = UserModule.create! valid_attributes
        patch user_module_url(user_module), params: { user_module: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user_module" do
      user_module = UserModule.create! valid_attributes
      expect {
        delete user_module_url(user_module)
      }.to change(UserModule, :count).by(-1)
    end

    it "redirects to the user_modules list" do
      user_module = UserModule.create! valid_attributes
      delete user_module_url(user_module)
      expect(response).to redirect_to(user_modules_url)
    end
  end
end
